networks:
  app_network:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my-app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network  

  backend:
    image: phuong06061994/java-demo:tag
    container_name: backend-app
    ports:
      - "50002:8080"
    networks:
      - app_network  
    depends_on:
      - postgres

  frontend:
    image: phuong06061994/angular-demo:tag
    container_name: frontend-app
    ports:
      - "3000:80"
    networks:
      - app_network  
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    networks:
      - app_network  
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d

volumes:
  postgres_data:
