replicaCount: 1

image:
  repository: registry
  tag: "2"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  host: localhost
  annotations: 
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
  path: /docker
  pathType: Prefix

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
