version: '3.8'

networks:
  jenkins_network:
    driver: bridge

services:
  jenkins-master:
    build: ./jenkins-master
    container_name: jenkins-master
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins_network
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      JENKINS_ADMIN_ID: admin
      JENKINS_ADMIN_PASSWORD: admin_password
    entrypoint: /bin/bash -c "chmod -R 444 /var/jenkins_home && /usr/local/bin/jenkins.sh"

  java-slave:
    build: ./java-slave
    container_name: java-slave
    ports:
      - "5000:5000"
    networks:
      - jenkins_network
    environment:
      JENKINS_MASTER_URL: http://jenkins-master:8080
      SWARM_CLIENT_NAME: java-slave
      SWARM_CLIENT_LABELS: "java"
      SWARM_CLIENT_EXECUTORS: 2
      JENKINS_USERNAME: admin
    depends_on:
      - jenkins-master
    volumes:
      - jenkins_home:/var/jenkins_home

  node-slave:
    build: ./node-slave
    container_name: node-slave
    ports:
      - "3000:3000"
    networks:
      - jenkins_network
    environment:
      JENKINS_MASTER_URL: http://jenkins-master:8080
      SWARM_CLIENT_NAME: node-slave
      SWARM_CLIENT_LABELS: "node"
      SWARM_CLIENT_EXECUTORS: 2
      JENKINS_USERNAME: admin
    depends_on:
      - jenkins-master
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
