version: '3.8'

networks:
  app_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
        
services:
  frontend:
    image: node:18
    container_name: frontend-app
    ports:
      - "3000:3000"
    networks:
      app_network:
        ipv4_address: 172.28.0.10 
      
  backend:
    image: phuong06061994/java-demo:2
    container_name: backend-app
    ports:
      - "5000:5000"
    networks:
      app_network:
        ipv4_address: 172.28.0.11 

  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my-app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      app_network:
        ipv4_address: 172.28.0.12 
      
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    app_network:
        ipv4_address: 172.28.0.13 
      
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  postgres_data:
  