apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: {{ .Values.nginx.service.port }}
      targetPort: {{ .Values.nginx.service.targetPort }}
  type: {{ .Values.nginx.service.type }}

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: {{ .Values.postgresql.service.port }}
      targetPort: {{ .Values.postgresql.service.targetPort }}
  type: {{ .Values.postgresql.service.type }}
